image: node:latest
cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/
stages:
  - validate
  - test
  - build
  - release
  - deploy

install:
  stage: .pre
  script:
    - npm ci --cache .npm --prefer-offline
