image: node-alpine 
cache: 
  key:
    files:
        - package-lock.json
    paths: 
      - node_modules/
      - .npm/
stages:
  - validate
  - test
  - build
  - release
  - deploy

install:
  stage: .pre
  script:
    # define cache dir & use it npm!
    - npm ci --cache .npm --prefer-offline
