name: CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci --cache .npm --prefer-offline