name: CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci --cache .npm --prefer-offline

  lint:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - run: npm ci --cache .npm --prefer-offline
      - run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    needs: [install, lint]
    steps:
      - uses: actions/checkout@v4
      - run: npm ci --cache .npm --prefer-offline
      - run: npm test